### ISSUE TITLE
Command Line Error

### ISSUE THREAD

**Issue by cukabeka** [matthewwithanm/python-markdownify#74]
Hi, 
I stumbled across this script, thanks for publishing this. I tried it on a HTML file with the following command, but can't interpret the error. I'm on a Mac with homebrew / python3.

`markdownify test.html > test.md`

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/markdownify", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/main.py", line 61, in main
    print(markdownify(**vars(args)))
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/__init__.py", line 395, in markdownify
    return MarkdownConverter(**options).convert(html)
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/__init__.py", line 97, in convert
    return self.convert_soup(soup)
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/__init__.py", line 100, in convert_soup
    return self.process_tag(soup, convert_as_inline=False, children_only=True)
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/__init__.py", line 143, in process_tag
    text += self.process_tag(el, convert_children_as_inline)
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/__init__.py", line 143, in process_tag
    text += self.process_tag(el, convert_children_as_inline)
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/__init__.py", line 143, in process_tag
    text += self.process_tag(el, convert_children_as_inline)
  [Previous line repeated 16 more times]
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/__init__.py", line 148, in process_tag
    text = convert_fn(node, text, convert_as_inline)
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/__init__.py", line 181, in convert_tag
    return self.convert_hn(n, el, text, convert_as_inline)
  File "/opt/homebrew/lib/python3.10/site-packages/markdownify/__init__.py", line 268, in convert_hn
    style = self.options['heading_style'].lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by AlexVonB** [comment]
Thank you! This should be fixed now: https://github.com/matthewwithanm/python-markdownify/releases/tag/0.11.5 :)

**Comment by cukabeka** [comment]
Thank you! It works now
