### ISSUE TITLE
TypeError: MarkdownConverter.convert_hn() missing 1 required positional argument: 'convert_as_inline'

### ISSUE THREAD

**Issue by zfang** [matthewwithanm/python-markdownify#93]
markdownify==0.11.6
```
23/08/16 22:12:11 WARN BlockManager: Putting block rdd_12_76 failed due to exception org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/spark/.local/lib/python3.10/site-packages/markdownify/__init__.py", line 395, in markdownify
    return MarkdownConverter(**options).convert(html)
  File "/home/spark/.local/lib/python3.10/site-packages/markdownify/__init__.py", line 97, in convert
    return self.convert_soup(soup)
  File "/home/spark/.local/lib/python3.10/site-packages/markdownify/__init__.py", line 100, in convert_soup
    return self.process_tag(soup, convert_as_inline=False, children_only=True)
  File "/home/spark/.local/lib/python3.10/site-packages/markdownify/__init__.py", line 143, in process_tag
    text += self.process_tag(el, convert_children_as_inline)
  File "/home/spark/.local/lib/python3.10/site-packages/markdownify/__init__.py", line 148, in process_tag
    text = convert_fn(node, text, convert_as_inline)
TypeError: MarkdownConverter.convert_hn() missing 1 required positional argument: 'convert_as_inline'
.
```

**Comment by AlexVonB** [comment]
Closed by https://github.com/matthewwithanm/python-markdownify/commit/3466061ca9d33afd06532e2e79b418b8e478d66b , thanks!
